# Generated by Django 6.0.3 on 2026-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('other', 'Other')], max_length=20)),
                ('problem_description', models.TextField()),
                ('pickup_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('pickup_map_location', models.URLField(blank=True, help_text='Paste Google Maps location link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('repairing', 'Repairing'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
    ]
